const IMAGES = {
    home: require('./home.PNG'),
    explore: require('./explore.PNG'),
    cover1: require('./cover 1.png'),
    cover2: require('./cover 2.png'),
    cover3: require('./cover 3.png'),
    cover4: require('./cover 4.png'),
    cover5: require('./cover 5.png'),
    cover6: require('./cover 6.png'),
    cover7: require('./cover 7.png'),
    cover8: require('./cover 8.png'),
    cover9: require('./cover 9.png'),
    cover10: require('./cover 10.png'),
    cover11: require('./cover 11.png'),
    cover12: require('./cover 12.png'),
    cover13: require('./cover 13.png'),
    comment: require('./comment.PNG'),
    add: require('./add.PNG'),
    like: require('./like.PNG'),
    logo: require('./logo.PNG'),
    messenger: require('./messenger.PNG'),
    option: require('./option.PNG'),
    profile_pic: require('./profile-pic.png'),
    save: require('./save.PNG'),
    send: require('./send.PNG'),
    smile: require('./smile.PNG'),
    createPost: require('./6537820.png')
}

export default IMAGES